on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build
      run: dotnet build src/Tubes.sln --configuration Release
    - name: Test
      run: dotnet test src/Tubes.sln --configuration Release --no-build
